/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as ApiPublicMyraaRouteImport } from './routes/api/public/myraa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMyraaRoute = ApiPublicMyraaRouteImport.update({
  id: '/api/public/myraa',
  path: '/api/public/myraa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/myraa': typeof ApiPublicMyraaRoute
  '/api/public/version': typeof ApiPublicVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/myraa': typeof ApiPublicMyraaRoute
  '/api/public/version': typeof ApiPublicVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/myraa': typeof ApiPublicMyraaRoute
  '/api/public/version': typeof ApiPublicVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/myraa' | '/api/public/version'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/myraa' | '/api/public/version'
  id: '__root__' | '/' | '/api/public/myraa' | '/api/public/version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicMyraaRoute: typeof ApiPublicMyraaRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/myraa': {
      id: '/api/public/myraa'
      path: '/api/public/myraa'
      fullPath: '/api/public/myraa'
      preLoaderRoute: typeof ApiPublicMyraaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicMyraaRoute: ApiPublicMyraaRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
